### ISSUE TITLE
 Train and eval size of Cycle-GAN

### ISSUE THREAD

**Issue by sshaoshuai** [liyunsheng13/BDL#11]
Hi,
Thanks for sharing the codes!
I have a small question about the training of Cycle-GAN. 
For the training of Cycle-GAN, the input images are resized to 256x256 for the training. But the original size of image is 1024x564 (such as GTA), so after training of Cycle-GAN, how could you generate the transfered image of GTA in the original size (1024x564) ? 
If you directly feed the original GTA image to the model trained with 256x256, does it harm the transfered performance?
Thanks very much and looking forward to your reply!

**Comment by liyunsheng13** [comment]
What I did to train Cycle-GAN is to resize the image to 1024*X or X*1024 and then crop a patch with size 452*452. You can choose other size based on the GPU you use.

**Comment by sshaoshuai** [comment]
Ok, Thank you!  I will try it.
