### ISSUE TITLE
how did you make initial weight?

### ISSUE THREAD

**Issue by MyeongJin-Kim** [liyunsheng13/BDL#13]
Before training FCN8s-VGG16 model, I test initial weight you provide.
Then I got 30.0 mIoU.
In paper, you wrote imagenet pretrained model. 
But in my thought, initial model's high mIoU means it is trained on supervision of segmentation data.
How did you make the initial weight??

**Comment by liyunsheng13** [comment]
Just train the model with the synthetic data for initialization.

**Comment by MyeongJin-Kim** [comment]
Thanks for fast answer!
When I train model with imagenet pretrained weight, 
Deeplab-ResNet101 model switch from classification feature to segmentation feature very fast.
But for FCN8s-VGG16, it shows extremely show transform.
Did you get the same pattern??

**Comment by liyunsheng13** [comment]
I'm sorry I cannot remember. I think different initialization should not cause any difference to the final adaptation results. But like you said, the adaptation speed might be different.

**Comment by MyeongJin-Kim** [comment]
Thanks!
When I tested Deeplab-V2 init weight, it seems not trained on synthetic data.
Is there any special reason for different initialization (classification feature / segmentation feature) for different model(Deeplab / FCN8s)?

**Comment by liyunsheng13** [comment]
No special reason. You can try different ways to initialize the model. It won't make any difference on the results

**Comment by MyeongJin-Kim** [comment]
Thanks a lot!
