### ISSUE TITLE
how did you set discriminator's weight?

### ISSUE THREAD

**Issue by MyeongJin-Kim** [liyunsheng13/BDL#14]
In inner loop for SSL, if N=2, segmentation network is trained 3 times in a row. 
When training segmentation network, how did you set the discriminator's weight?
Initialize discriminator every time or use previous discriminator's weight??

Also same question for outer loop's weight.

**Comment by liyunsheng13** [comment]
The weight for the discriminator is randomly initialized.

**Comment by MyeongJin-Kim** [comment]
Thanks for the comment!

**Comment by MyeongJin-Kim** [comment]
One more question!

If discriminator is randomly initialized, when train again with previous segmentation weight, mIoU drop at early stage. Did you get the same pattern?

**Comment by liyunsheng13** [comment]
I don't quite understand your question. what do you mean by "train again"? If you mean training a new model with pseudo labels, I don't have overfitting problem.
