### ISSUE TITLE
SSL for SYNTHIA

### ISSUE THREAD

**Issue by MyeongJin-Kim** [liyunsheng13/BDL#19]
Hi 
When I train segmentation network with the pseudo labels with your code,
for GTA5, training is stable and mIoU is incrementally increases.
But for SYNTHIA, it shows different pattern.
The mIoU first steeply rise in early iteration, but decrease as train proceed.
I think that ,because layout gap between SYNTHIA and Cityscapes is much bigger, overfitting problem occurs in SYNTHIA setting.
Did you get the same pattern?

**Comment by liyunsheng13** [comment]
Without SSL, overfitting is a serious problem for both GTA5 and SYNTHIA. But with SSL, I think the mIoU is much more stable. I don't see a big overfitting problem for SYNTHIA. If you see big overfitting, you can try to decrease the lr for discriminator.
