### ISSUE TITLE
About the training on CycleGAN

### ISSUE THREAD

**Issue by Solacex** [liyunsheng13/BDL#22]
Hello, 
Which files in official CycleGAN code should be replaced by your code? I try to replace the ./modes/ ./options/ , but it doesn't work .

**Comment by liyunsheng13** [comment]
Could you let me know the specific error you got?

**Comment by Solacex** [comment]
> Could you let me know the specific error you got?

Hello, Thanks for your prompt reply~
The question on configurations has been solved by myself.
