### ISSUE TITLE
GTA5 image size

### ISSUE THREAD

**Issue by Turlan** [liyunsheng13/BDL#32]
What I did to train Cycle-GAN is to resize the image to 1024*X or X*1024 and then crop a patch with size 452*452. You can choose other size based on the GPU you use.

_Originally posted by @liyunsheng13 in https://github.com/liyunsheng13/BDL/issues/11#issuecomment-513028927_

The original size of GTA5 images is 1914x1052, after resize the width of the images to 1024, then the hight should be (1052 * 1024 // 1914) = 562. The image you provided is 1024x564, so is there any extra processing such as padding?

**Comment by liyunsheng13** [comment]
No.
