### ISSUE TITLE
Train CycleGAN

### ISSUE THREAD

**Issue by iiREIG** [liyunsheng13/BDL#36]
Thanks for sharing the codes!
I have a quetion about training Cycle-GAN.
Did you use all 24966 GTA5 images and 2975 Cityscapes images for training the Cycle-GAN?
When i traning it on RTX2080tI , it will take a few days.

**Comment by liyunsheng13** [comment]
Yes. I use all the images. It might take around 4 days .

**Comment by JialeTao** [comment]
Hi, I think your training speed is still much more faster than that of my situation. In fact, I found that single-image training takes 0.9 second and it will take around a month to train all images for 200 epochs. I trained this on a single RTX2080ti with crop size 380. How did you train so fast , are there some skills I've forgotten? @liyunsheng13 @iiREIG
