### ISSUE TITLE
ssl.py

### ISSUE THREAD

**Issue by lqycrystal** [liyunsheng13/BDL#4]
could you give more explanation about using self supervised training?

**Comment by liyunsheng13** [comment]
The question is not very clear to me. What kind of explanation do you need?

**Comment by lqycrystal** [comment]
> The question is not very clear to me. What kind of explanation do you need?
Is the source ground truth still matching with translated source data?

**Comment by liyunsheng13** [comment]
Yes. I don't quite get your question because I don't see any reason they don't match.
