### ISSUE TITLE
Bug in the DeepLab ResNet101 atrous convolution forward function 

### ISSUE THREAD

**Issue by akshaykulkarni07** [liyunsheng13/BDL#41]
In [this file](https://github.com/liyunsheng13/BDL/blob/master/model/deeplab.py), line numbers 115 to 119,

```    
    def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list) - 1):
            out += self.conv2d_list[i + 1](x)
            return out
```

The return statement is inside the for loop, instead of outside the for loop.

**Comment by liyunsheng13** [comment]
Thanks for letting me know. I have fixed it.

**Comment by akshaykulkarni07** [comment]
Could you also tell me whether this bug affects your paper results? Because atrous convolutions are important to get good segmentation outputs.

**Comment by liyunsheng13** [comment]
I don't think it will influence the result a lot. At least removing the bug won't worsen the result.
