### ISSUE TITLE
problem about loss become nan

### ISSUE THREAD

**Issue by du841021** [liyunsheng13/BDL#46]
hi,thanks for the code
I'm, trying to train GTA2Cityspace on VGG and DeepLab.
but no mater with or without self-supervised, after 2 iteration src seg loss will become nan. can you tell me how to fix it? thank you!

my environment:
CUDA Version: 11.1, pytorch-gpu:1.2.0
and here is my log on training self-supervised VGG:
![擷取選取區域_066](https://user-images.githubusercontent.com/19721275/104090086-247f2980-52af-11eb-9883-b1ba28dd61d3.png)

**Comment by liyunsheng13** [comment]
I'm not quite sure. Based on the hyper parameters you provide, it should be fine.
