### ISSUE TITLE
CycleGAN training problem

### ISSUE THREAD

**Issue by liyunsheng13** [liyunsheng13/BDL#6]
hi，When I train cyclegan, GA can easily turn the sky in GTAV into a tree. Do you know what the problem is?thank you @liyunsheng13

_Originally posted by @PJ1yang in https://github.com/liyunsheng13/BDL/issues/5#issuecomment-499867201_

**Comment by liyunsheng13** [comment]
You are right. This problem is hard to be solved. I think it is caused by the difference of the spatial layout between GTA5 and Cityscapes dataset. For GTA5, there is not a lot of trees in the sky part but the Cityscapes is different. When CycleGAN is trained, it realize that spatial layout difference and tries to convert it from source domain to the target domain. If you train CycleGAN with datasets that have larger domain gap, you can find this phenomenon more obvious. Right now, there is not a way to solve this problem. I suggest you to make the identity loss or the reconstruction perception loss more important. They might help.

**Comment by ghost** [comment]
Thanks for your advice
