### ISSUE TITLE
The description of the paper is inconsistent with the code 

### ISSUE THREAD

**Issue by jarvisWang0903** [liyunsheng13/BDL#7]
In the paper you say that L1 Loss is used for **l_per** , instead, you use mse loss in your code
[cycle _gan_model.py def compute_semantic_loss] ,which one is correct ?

**Comment by liyunsheng13** [comment]
I'm sorry that the L1 loss in the paper is a type. We will update a new version after CVPR. If you find any other inconsistency between the code and the paper, please ignore the paper. The released code is what I use to produce all the results in the paper. Thanks for pointing out the issue for us.

**Comment by jarvisWang0903** [comment]
Thanks for your considerate response and thanks for your open source code! :smile:
